let developers = [
    {
        login: 'NirPisatto',
        id: 76983137,
        node_id: 'MDQ6VXNlcjc2OTgzMTM3',
        avatar_url: 'https://avatars.githubusercontent.com/u/76983137?v=4',
        url: 'https://api.github.com/users/NirPisatto',
        html_url: 'https://github.com/NirPisatto',
        followers_url: 'https://api.github.com/users/NirPisatto/followers',
        following_url:
            'https://api.github.com/users/NirPisatto/following{/other_user}',
        gists_url: 'https://api.github.com/users/NirPisatto/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/NirPisatto/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/NirPisatto/subscriptions',
        organizations_url: 'https://api.github.com/users/NirPisatto/orgs',
        repos_url: 'https://api.github.com/users/NirPisatto/repos',
        events_url: 'https://api.github.com/users/NirPisatto/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/NirPisatto/received_events',
        type: 'User',
        site_admin: false,
        name: 'Pisatto',
        company: null,
        blog: '',
        location: null,
        email: null,
        hireable: null,
        bio: 'Hi, I dislike combination of words but unfortunately I am a code engineer. My favourite programming languages are JavaScript and Python. I am currently a frontend web engineer mainly working with Vue.js.',
        twitter_username: null,
        public_repos: 4,
        public_gists: 0,
        followers: 0,
        following: 0,
        created_at: '2021-01-05T02:53:30Z',
        updated_at: '2022-03-04T06:02:39Z',
        skills: [
            'JavaScript',
            'Python',
            'C/C++',
            'PHP',
            'SQL',
            'Firebase',
            'APIs',
            'Bootstrap',
            'Material Ui',
            'React.js',
            'Vue.js',
        ],
    },
    {
        login: 'hoklenghak',
        id: 89648857,
        node_id: 'MDQ6VXNlcjg5NjQ4ODU3',
        avatar_url: 'https://avatars.githubusercontent.com/u/89648857?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/hoklenghak',
        html_url: 'https://github.com/hoklenghak',
        followers_url: 'https://api.github.com/users/hoklenghak/followers',
        following_url:
            'https://api.github.com/users/hoklenghak/following{/other_user}',
        gists_url: 'https://api.github.com/users/hoklenghak/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/hoklenghak/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/hoklenghak/subscriptions',
        organizations_url: 'https://api.github.com/users/hoklenghak/orgs',
        repos_url: 'https://api.github.com/users/hoklenghak/repos',
        events_url: 'https://api.github.com/users/hoklenghak/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/hoklenghak/received_events',
        type: 'User',
        site_admin: false,
        name: 'Lenghak Hok',
        company: null,
        blog: '',
        location: null,
        email: null,
        hireable: null,
        bio: null,
        twitter_username: null,
        public_repos: 1,
        public_gists: 0,
        followers: 0,
        following: 0,
        created_at: '2021-08-27T14:14:19Z',
        updated_at: '2022-01-05T13:35:18Z',
        skills: [],
    },
    {
        login: 'ChamroeunProMaxQ',
        id: 89696388,
        node_id: 'MDQ6VXNlcjg5Njk2Mzg4',
        avatar_url: 'https://avatars.githubusercontent.com/u/89696388?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/ChamroeunProMaxQ',
        html_url: 'https://github.com/ChamroeunProMaxQ',
        followers_url:
            'https://api.github.com/users/ChamroeunProMaxQ/followers',
        following_url:
            'https://api.github.com/users/ChamroeunProMaxQ/following{/other_user}',
        gists_url:
            'https://api.github.com/users/ChamroeunProMaxQ/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/ChamroeunProMaxQ/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/ChamroeunProMaxQ/subscriptions',
        organizations_url: 'https://api.github.com/users/ChamroeunProMaxQ/orgs',
        repos_url: 'https://api.github.com/users/ChamroeunProMaxQ/repos',
        events_url:
            'https://api.github.com/users/ChamroeunProMaxQ/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/ChamroeunProMaxQ/received_events',
        type: 'User',
        site_admin: false,
        name: null,
        company: null,
        blog: '',
        location: null,
        email: null,
        hireable: null,
        bio: null,
        twitter_username: null,
        public_repos: 0,
        public_gists: 0,
        followers: 0,
        following: 0,
        created_at: '2021-08-28T14:23:56Z',
        updated_at: '2022-02-15T14:26:24Z',
        skills: [],
    },
    {
        login: 'YornChanvisal',
        id: 89696454,
        node_id: 'MDQ6VXNlcjg5Njk2NDU0',
        avatar_url: 'https://avatars.githubusercontent.com/u/89696454?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/YornChanvisal',
        html_url: 'https://github.com/YornChanvisal',
        followers_url: 'https://api.github.com/users/YornChanvisal/followers',
        following_url:
            'https://api.github.com/users/YornChanvisal/following{/other_user}',
        gists_url: 'https://api.github.com/users/YornChanvisal/gists{/gist_id}',
        starred_url:
            'https://api.github.com/users/YornChanvisal/starred{/owner}{/repo}',
        subscriptions_url:
            'https://api.github.com/users/YornChanvisal/subscriptions',
        organizations_url: 'https://api.github.com/users/YornChanvisal/orgs',
        repos_url: 'https://api.github.com/users/YornChanvisal/repos',
        events_url:
            'https://api.github.com/users/YornChanvisal/events{/privacy}',
        received_events_url:
            'https://api.github.com/users/YornChanvisal/received_events',
        type: 'User',
        site_admin: false,
        name: null,
        company: null,
        blog: '',
        location: null,
        email: null,
        hireable: null,
        bio: null,
        twitter_username: null,
        public_repos: 1,
        public_gists: 0,
        followers: 0,
        following: 0,
        created_at: '2021-08-28T14:25:43Z',
        updated_at: '2022-02-19T14:07:26Z',
        skills: [],
    },
]

export default developers
